# Generated by Django 4.0.4 on 2022-05-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_newuser_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='default_address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='sem',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
