# Generated by Django 4.0.4 on 2022-05-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_content_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='roll_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
