# Generated by Django 4.0.4 on 2022-05-19 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_newuser_default_address_alter_newuser_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 22, 27, 18, 577964)),
        ),
        migrations.AddField(
            model_name='borrow',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 22, 27, 18, 577964)),
        ),
    ]
