# Generated by Django 4.0.4 on 2022-05-19 17:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_borrow_due_date_borrow_issue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='book',
        ),
        migrations.AddField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(db_column='book_name', default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.book'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 23, 3, 2, 201519)),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 23, 3, 2, 201519)),
        ),
    ]
