# Generated by Django 4.0.4 on 2022-05-23 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_borrow_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='course',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 10, 48, 36, 143811)),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(max_length=150),
        ),
    ]
