# Generated by Django 4.0.4 on 2022-05-26 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_book_edition_alter_borrow_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rack_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 21, 4, 41, 3783)),
        ),
    ]
