# Generated by Django 4.0.4 on 2022-05-26 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_book_rack_no_alter_borrow_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='submit',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 21, 8, 19, 112510)),
        ),
    ]
